from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_pdf(prediction, confidence):
    folder_path = "reports"

    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    filename = f"{folder_path}/Kidney_Report.pdf"

    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(150, 800, "Kidney Tumor Detection Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, 750, f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")

    c.drawString(50, 710, f"Prediction Result: {prediction}")
    c.drawString(50, 680, f"Confidence Score: {confidence}%")

    if prediction == "Tumor":
        recommendation = "Please consult a nephrologist immediately."
    else:
        recommendation = "Kidney appears normal. Routine monitoring recommended."

    c.drawString(50, 640, "Doctor Recommendation:")
    c.drawString(70, 610, recommendation)

    c.drawString(50, 550, "Generated by AI-Powered Kidney Tumor Detection System")

    c.save()

    return filename